# Mike McQuade
# dna-pair.pl
use strict;
use warnings;

# Initialize the variables
my $string = "TCCCATTTTTCAGATATCACGCTGACGGGTGGAGCAGAAAATGTCCGGCCGGATGATGGCATTCCTCCACTAGTCTAATCCCTCAGTCGGGGGGGCGAAGTGCACGCATTAAGCTGGCTCCCGACTGTACGTCAATATCGCGTAAGGCCGCTTTTCACGAAGGGGGACAGCAGGACCAGAGCCATCGTCAGGAGGCCGTTATTATGAGTTGACTCATTTAACTTGAAGGCCGTTATAGCACAATCGTTGCTCGGTGTGACCTCTCAGACACGTTCACGGCTCTCCAGGGACAAAATGGAATTTTTGATCTAGTAACGCGGAAGGTGCAGGCTCGCTGTTATCAGATTGTCAGCGACTTGCCACGGAACACTCATTCAGGTTGAAGTTAGCCTACAGCATGATCTCCAGCGACGAGCCTGGCTTACCTACTAAATGGCCTGAGGAACGAGTTCCTTAGAGCACGCAAATGTAGCACGTGTATGTACCGAAACGTGTAGAAATTAAAGACACCTATAGATCACTCGCATCCCAGATCAAATGAAGGGCTGAATTGGGCCGTCCGATGCTTTTAAGGTTTTAAGGCTCTTAACCGTTAGCCCAGATTGTATTGGCCCTTGTCCAAAGTTGCTATATTGCGTCCCCAAGAGGCTAAAGTCGATTTGGAGGTTTTGATGCTTATATTAGGAAAGTTTTCTAGCAGTATGGAGCGAATCGCGAGGGTAAGGCGCTTGCCACCTTGCGTGGTCTATCCAATGGCGGAATCCCGCTAAACGGGTAGGGGCCCTCTATCCACTGGCTAGGCTAGGTGCCTCGGAGATTGCAATGCTCCGCTTCGGTAGTCTTAAGTTTAGGAATGTATATGACAGCACTTACTGTTGGCAAATCCTGGGTAAATCCGAGCACTTCGTGTAGCTCCTTCTCCTATTTGTCAGTGTTAGGTAATGGTAGTGTAGTAAACCAAGGGAACTAGCA";
my $reverse = "";

# Append the opposite of each letter in the string to the new string, in reverse order
for (my $i = length($string)-1; $i >= 0; $i--) {
	if (substr($string,$i,1) eq 'A') {$reverse .= 'T';}
	elsif (substr($string,$i,1) eq 'C') {$reverse .= 'G';}
	elsif (substr($string,$i,1) eq 'G') {$reverse .= 'C';}
	elsif (substr($string,$i,1) eq 'T') {$reverse .= 'A';}
}

# Print the reverse string
print $reverse."\n";